version: 2
updates:
- package-ecosystem: maven
  directory: "/openchrom"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    tycho:
      patterns:
        - "org.eclipse.tycho*"
        - "tycho.version"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
