<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2012, 2025 Lablicate GmbH. All rights reserved. This program
	and the accompanying materials are made available under the terms of the
	Eclipse Public License v2.0 which accompanies this distribution, and is available
	at http://www.eclipse.org/legal/epl-v20.html Contributors: Dr. Philip Wenig
	- created the pom to build the plug-ins -->
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.openchrom</groupId>
	<artifactId>master</artifactId>
	<version>1.6.2-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<!-- versions for plugins to use -->
		<tycho.version>5.0.1</tycho.version>
		<maven-install-plugin.version>3.1.4</maven-install-plugin.version>
		<cbi-version>1.5.2</cbi-version>
		<!-- definition of the target to use -->
		<tycho.target.groupId>net.openchrom</tycho.target.groupId>
		<tycho.target.artifactId>net.openchrom.targetplatform</tycho.target.artifactId>
		<tycho.target.version>${project.version}</tycho.target.version>
		<skip.install>false</skip.install>
		<!-- other settings -->
		<tycho.groupid>org.eclipse.tycho</tycho.groupid>
		<maven.groupid>org.apache.maven.plugins</maven.groupid>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<!-- about dialog -->
		<maven.build.timestamp.format>yyyyMMdd-HHmm</maven.build.timestamp.format>
		<buildTimestamp>${maven.build.timestamp}</buildTimestamp>
		<buildId>${buildTimestamp}</buildId>
		<releaseName>1.6.2</releaseName>
	</properties>

	<repositories>
		<repository>
			<id>jre-updates</id>
			<url>https://download.eclipse.org/justj/jres/21/updates/release/latest/</url>
			<layout>p2</layout>
		</repository>
	</repositories>

	<build>
		<!-- PLUGINS -->
		<plugins>
			<plugin>
				<groupId>${tycho.groupid}</groupId>
				<artifactId>tycho-packaging-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<archive>
						<addMavenDescriptor>false</addMavenDescriptor>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>${tycho.groupid}</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho.version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>${tycho.groupid}</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<target>
						<artifact>
							<groupId>${tycho.target.groupId}</groupId>
							<artifactId>${tycho.target.artifactId}</artifactId>
							<version>${tycho.target.version}</version>
						</artifact>
					</target>
					<environments>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>aarch64</arch>
						</environment>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>aarch64</arch>
						</environment>
					</environments>
					<dependency-resolution>
						<profileProperties>
							<org.eclipse.justj.buildtime>true</org.eclipse.justj.buildtime>
						</profileProperties>
					</dependency-resolution>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>${tycho.groupid}</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<excludes>
						<exclude>**/*TestCase.java</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>${maven.groupid}</groupId>
				<artifactId>maven-install-plugin</artifactId>
				<version>${maven-install-plugin.version}</version>
				<configuration>
					<skip>${skip.install}</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>process-about.mappings</id>
						<phase>prepare-package</phase>
						<configuration>
							<outputDirectory>${project.build.directory}</outputDirectory>
							<overwrite>true</overwrite>
							<resources>
								<resource>
									<directory>${basedir}</directory>
									<includes>
										<include>about.mappings</include>
									</includes>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
						<goals>
							<goal>copy-resources</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-packaging-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<additionalFileSets>
						<fileSet>
							<directory>${project.build.directory}</directory>
							<includes>
								<include>about.mappings</include>
							</includes>
						</fileSet>
					</additionalFileSets>
				</configuration>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-p2-director-plugin</artifactId>
					<version>${tycho.version}</version>
					<executions>
						<execution>
							<id>materialize-products</id>
							<goals>
								<goal>materialize-products</goal>
							</goals>
							<phase>install</phase>
						</execution>
						<execution>
							<id>archive-products</id>
							<goals>
								<goal>archive-products</goal>
							</goals>
							<phase>install</phase>
						</execution>
					</executions>
					<configuration>
						<formats>
							<linux>tar.gz</linux>
							<macosx>tar.gz</macosx>
						</formats>
						<storeCreationTime>false</storeCreationTime>
						<products>
							<product>
								<rootFolders>
									<macosx>OpenChrom.app</macosx>
								</rootFolders>
							</product>
						</products>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-p2-repository-plugin</artifactId>
					<version>${tycho.version}</version>
					<configuration>
						<includeAllDependencies>true</includeAllDependencies>
						<skipArchive>true</skipArchive>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<profiles>
		<profile>
			<id>ci</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-p2-director-plugin</artifactId>
						<executions>
							<execution>
								<id>materialize-products</id>
								<goals>
									<goal>materialize-products</goal>
								</goals>
								<phase>none</phase>
							</execution>
							<execution>
								<id>archive-products</id>
								<phase>none</phase>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>codesign</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-jarsigner-plugin</artifactId>
						<version>3.1.0</version>
						<configuration>
							<keystore>${jarsigner.keystore}</keystore>
							<alias>${jarsigner.alias}</alias>
							<storepass>${jarsigner.storepass}</storepass>
							<keypass>${jarsigner.keypass}</keypass>
						</configuration>
						<executions>
							<execution>
								<id>sign</id>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
